[tool.poetry]
name = "string-to-code"
version = "0.2.15"
description = "Generates a piece of messy code in a given language displaying a given string "
authors = ["piotr.idzik <vil02@o2.pl>"]
readme = "./string_to_code/README.md"
license = "MIT"
packages = [{include = "string_to_code"}]
repository = "https://github.com/vil02/string_to_code_proj"
keywords = ["code-generation"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "8.3.4"
pytest-mock = "3.14.0"
pylint = "3.3.3"
flake8 = "7.1.1"
flake8-pytest-style = "2.0.0"
ruff = "0.8.4"
coverage = "7.6.10"
black = "24.10.0"
mypy = "1.14.0"
bandit = "1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
