[tool.poetry]
name = "string-to-code"
version = "0.2.7"
description = "Generates a piece of messy code in a given language displaying a given string "
authors = ["piotr.idzik <vil02@o2.pl>"]
readme = "./string_to_code/README.md"
license = "MIT"
packages = [{include = "string_to_code"}]
repository = "https://github.com/vil02/string_to_code_proj"
keywords = ["code-generation"]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = ">=7.0"
pytest-mock = ">3.0"
pylint = ">=2.0"
flake8 = ">=5.0"
coverage = ">=6.0"
black = ">=21.0"
mypy = ">=1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
